# -*- coding: utf-8 -*-
"""BMI706_ProjectDataPrep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Da5zms1-fSLydiKzIqdeFtBDiH0dkv7k
"""

import pandas as pd
import numpy as np
import zipfile
import os

"""## Load Datasets"""

!kaggle datasets download nguyenvy/nhanes-19882018

# load data
with zipfile.ZipFile('/content/nhanes-19882018.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/nhanes_19882018_data')

demographics_path = os.path.join('/content/nhanes_19882018_data', 'demographics_clean.csv')
questionnaire_path = os.path.join('/content/nhanes_19882018_data', 'questionnaire_clean.csv')
mortality_path = os.path.join('/content/nhanes_19882018_data', 'mortality_clean.csv')

# Load the CSV file into a DataFrame
demographics_df = pd.read_csv(demographics_path,index_col=0)
questionnaire_df = pd.read_csv(questionnaire_path,index_col=0)
mortality_df = pd.read_csv(mortality_path,index_col=0)

demographics_df

questionnaire_df

mortality_df